export const typographies = {
    H_1: 'h1',
    H_2: 'h2',
    H_3: 'h3',
    H_4: 'h4',
    H_5: 'h5',
    H_6: 'h6',
    SUBTITLE_1: 'subtitle-1',
    SUBTITLE_2: 'subtitle-2',
    BODY_1: 'body-1',
    BODY_2: 'body-2',
    BTN: 'button',
    CAPTION: 'caption',
    OVERLINE: 'overline',
} as const;
