export type ThemeColors = {
  black: string;
  white: string;
  light: string;
  shadowLight: string;
  shadowDark: string;
  strokeGray: string;
  darkBg: string;
  darkGray: string;
  lightTextGray: string;
  primaryDefault: string;
  primaryHovered: string;
  blueGray: string;
  blueGrayLight: string;
  gray: string;
  textGray: string;
  neutralLight: string;
  shuttleGray: string;
  ebonyGray: string;
  green: string;
  red: string;
  yellow: string;
  bayouxBlue: string;
};
